version: '3.7'
services:
  node-red:
    container_name: node-red-container
    build: 
      context: .
      dockerfile: ./node-red/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "1880:1880"
