version: '3.7'
services:
  node-red-sample:
    container_name: node-red-container-sample
    build:
      context: .
      dockerfile: ./node-red/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "1880:1880"
